
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/appweb/">Appweb Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://embedthis.com/blog/categories/Appweb">Appweb News</a>
                        <a class="item" href="https://github.com/embedthis/appweb">Repository</a>
                        <a class="item" href="https://embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
