{
    title:  'HTTP Standards',
    crumbs: [
        { 'Reference Guide': '../ref/' },
        { 'Standards': '../standards/' },
    ],
}
            <h1>HTTP Standards</h1>
            <p>The Standards guide contains references to the specifications that govern the HTTP protocol.</p>
            <table title="Standards" class="ui table segment">
                <thead>
                    <tr>
                        <th>Topic</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td><a href="https://http2.github.io/http2-spec/">HTTP/2</a></td>
                    <td>The HTTP/2 communications protocol specification.</td>
                </tr>
                <tr>
                    <td><a href="https://http2.github.io/http2-spec/compression.html">HTTP/2 HPACK</a></td>
                    <td>The HTTP/2 header compression specification.</td>
                </tr>
                <tr>
                    <td><a href="http://www.w3.org/Protocols/rfc2616/rfc2616.html">HTTP/1.1</a></td>
                    <td>The HTTP communications protocol specification.</td>
                </tr>
                <tr>
                    <td><a href="http://www.w3.org/CGI/">CGI 1.1</a></td>
                    <td>The Common Gateway Interface 1.1 protocol specification.</td>
                </tr>
                <tr>
                    <td><a href="http://www.ietf.org/rfc/rfc1867.txt">File Upload</a></td>
                    <td>The Form-based file HTML upload specification.</td>
                </tr>
                <tr>
                    <td><a href="http://tools.ietf.org/html/rfc6455">WebSockets RFC 6455</a></td>
                    <td>The WebSockets Protocol.</td>
                </tr>
                <tr>
                    <td><a href="http://dev.w3.org/html5/websockets/">WebSocket API</a></td>
                    <td>The Javascript WebSockets API.</td>
                </tr>
                </tbody>
            </table>
