{
    title:  'Man Pages',
    crumbs: [
        { "Developer's Guide": '../users/' },
    ],
}
        <h1>Manual Pages</h1>
        <p>This Appweb distribution provides manual pages that can be viewed (on Unix-like systems) using the systems
        <strong>man</strong> command. Text copies of the pages are included below:</p>
        <table title="Man Pages" class="ui table segment">
            <thead>
                <tr>
                    <th class="two wide">Topic</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td><a href="../man/appweb.html">appweb</a></td>
                <td>Appweb web server program.</td>
            </tr>
            <tr>
                <td><a href="../man/appman.html">appman</a></td>
                <td>Appweb manager program.</td>
            </tr>
            <tr>
                <td><a href="../man/appwebMonitor.html">appwebMonitor</a></td>
                <td>Appweb monitor program (windows).</td>
            </tr>
            <tr>
                <td><a href="../man/esp.html">appweb-esp</a></td>
                <td>ESP Web Framework application generator.</td>
            </tr>
            <tr>
                <td><a href="../man/authpass.html">authpass</a></td>
                <td>Utility program to manage user authorization and passwords.</td>
            </tr>
            <tr>
                <td><a href="../man/http.html">http</a></td>
                <td>Http client program.</td>
            </tr>
            <tr>
                <td><a href="../man/makerom.html">makerom</a></td>
                <td>Compiling files into ROM.</td>
            </tr>
            <tr>
                <td><a href="../man/regexp.html">regexp</a></td>
                <td>Regular expressions &mdash; Used in routes.</td>
            </tr>
            </tbody>
        </table>
