<!DOCTYPE html>
<html lang="eng">
<head>
<title>AppwebMonitor Man Page</title>
</head>
<HTML>
<BODY>
<PRE>
<!-- Manpage converted by man2html 3.0.1 -->

</PRE>
<H2>SYNOPSIS</H2><PRE>
       <B>appwebMonitor</B> [<I>--manage</I>] [<I>--stop</I>]


</PRE>
<H2>DESCRIPTION</H2><PRE>
       The appwebMonitor program runs in the Windows tray and provides visual
       feedback and control over the Appweb and Appweb manager process. Right-
       click to display the Monitor menu. From this menu, you can start or stop
       Appweb and launch the management console. Double-click will launch a
       browser homed to the web server home page.


</PRE>
<H2>OPTIONS</H2><PRE>
       <B>--manage</B>
              Launch a browser to display the Appweb management console. This is
              currently not implemented.

       <B>--stop</B> Stop the currently executing Monitor program.


</PRE>
<H2>REPORTING BUGS</H2><PRE>
       Report bugs to dev@embedthis.com.


</PRE>
<H2>COPYRIGHT</H2><PRE>
       Copyright © Embedthis Software.


</PRE>
<H2>SEE ALSO</H2><PRE>
       appweb



appwebMonitor                      March 2014                   <B>APPWEBMONITOR(1)</B>
</PRE>
<HR>
<ADDRESS>
Man(1) output converted with
<a href="http://www.oac.uci.edu/indiv/ehood/man2html.html">man2html</a>
</ADDRESS>
</BODY>
</HTML>
</html>