<!DOCTYPE html>
<html lang="eng">
<head>
<title>Appweb Man Page</title>
</head>
<HTML>
<BODY>
<PRE>
<!-- Manpage converted by man2html 3.0.1 -->

</PRE>
<H2>SYNOPSIS</H2><PRE>
       <B>appweb</B> <B>[options]</B>
       <B>appweb</B> <B>[options]</B> <B>[IP][:port]</B> <B>[documentRoot]</B>

       <B>appweb</B>
           <B>--config</B> <B>configFile</B>
           <B>--chroot</B> <B>directory</B>
           <B>--debugger</B>
           <B>--exe</B> <B>path</B>
           <B>--home</B> <B>directory</B>
           <B>--log</B> <B>logSpec</B>
           <B>--name</B> <B>uniqueName</B>
           <B>--threads</B> <B>threads</B>
           <B>--trace</B> <B>traceSpec</B>
           <B>--version</B>
           <B>--verbose</B>
           <B>--DIGIT</B>
           <B>[IP][:port]</B> <B>[documentRoot]</B>


</PRE>
<H2>DESCRIPTION</H2><PRE>
       Appweb is a compact embedded HTTP web server.  It is a fast, small-
       footprint, multi-threaded, standards-based, portable server developed for
       use by embedded devices and applications.  It can run as a stand-alone
       web server or the Appweb library can be embedded in applications.

       Appweb supports HTTP/1.1, HTTP/2, SSL, digest and basic authentication,
       virtual hosting, ranged requests, chunked transfers, file upload, CGI,
       FastCGI, Proxy and security limits.  Appweb has an Apache style
       configuration file and supports the ESP and PHP web frameworks.

       Appweb normally reads the <B>appweb.conf</B> file for configuration directives.
       However, if appweb is invoked with an IP address or port number on the
       command line, Appweb will not read the configuration file. Rather it will
       listen for requests on the specified IP:PORT address. If the PORT
       component is omitted, Appweb will listen on port 80. If the IP address is
       omitted and a port is supplied, Appweb will listen on all network
       interfaces.

       Appweb responds to the SIGUSR2 signal and toggles the trace level from 2
       to 4 and vice-versa. Appweb responds to the SIGINFO|SIGPWR signal and
       emits operational stats to the trace log.


</PRE>
<H2>OPTIONS</H2><PRE>
       <B>--config</B> <B>filename</B>
              Define the name of the Appweb configuration file. This is by
              default <B>appweb</B>.

       <B>--chroot</B> <B>directory</B>
              Change the system root directory for Appweb. This creates a chroot
              jail so that the Appweb process cannot access any files outside
              the given directory.

       <B>--log</B> <B>logSpec</B>
              Name the Appweb log file. This will override the ErrorLog
              directive in the configuration file. The syntax is:

              --log logName[:logLevel]

       <B>--name</B> <B>NAME</B>
              Define a unique name for this instance of Appweb. Useful for ps
              -ef listings.

       <B>--trace</B> <B>traceSpec</B>
              Name the Appweb request trace file. This will override the
              TraceLog directive in the configuration file.  The syntax is:

              --trace traceName[:traceLevel]

       <B>--verbose</B>
              Shorthand for --log stdout:4. The <B>-v</B> option is an alias for
              --verbose.

       <B>--version</B>
              Output the product version number.

       <B>--DIGIT</B>
              Shorthand for --log stdout:DIGIT --trace stdout:DIGIT.


</PRE>
<H2>FILES</H2><PRE>
       <B>/etc/appweb/appweb.conf</B>
       <B>/var/www/appweb-default</B>
       <B>/usr/local/lib/appweb</B>
       <B>/var/log/appweb</B>


</PRE>
<H2>REPORTING BUGS</H2><PRE>
       Report bugs to dev@embedthis.com.


</PRE>
<H2>COPYRIGHT</H2><PRE>
       Copyright © Embedthis Software.


</PRE>
<H2>SEE ALSO</H2><PRE>
       appman authpass esp http



appweb                             March 2014                          <B>APPWEB(1)</B>
</PRE>
<HR>
<ADDRESS>
Man(1) output converted with
<a href="http://www.oac.uci.edu/indiv/ehood/man2html.html">man2html</a>
</ADDRESS>
</BODY>
</HTML>
</html>