#include "osdep.h"

#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#define MBEDTLS_AESNI_C
#define MBEDTLS_AES_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_BLOWFISH_C
#define MBEDTLS_CCM_C
#define MBEDTLS_CERTS_C
#define MBEDTLS_CHACHA20_C
#define MBEDTLS_CHACHAPOLY_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_CIPHER_MODE_CFB
#define MBEDTLS_CIPHER_MODE_CTR
#define MBEDTLS_CIPHER_MODE_OFB
#define MBEDTLS_CIPHER_MODE_XTS
#define MBEDTLS_CIPHER_PADDING_ONE_AND_ZEROS
#define MBEDTLS_CIPHER_PADDING_PKCS7
#define MBEDTLS_CIPHER_PADDING_ZEROS
#define MBEDTLS_CIPHER_PADDING_ZEROS_AND_LEN
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_DEBUG_C
#define MBEDTLS_DES_C
#define MBEDTLS_DHM_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDH_LEGACY_CONTEXT
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECDSA_DETERMINISTIC
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_BP256R1_ENABLED
#define MBEDTLS_ECP_DP_BP384R1_ENABLED
#define MBEDTLS_ECP_DP_BP512R1_ENABLED
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define MBEDTLS_ECP_DP_CURVE448_ENABLED
#define MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_ERROR_C
#define MBEDTLS_ERROR_STRERROR_DUMMY
#define MBEDTLS_FS_IO
#define MBEDTLS_GCM_C
#define MBEDTLS_GENPRIME
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_TIME
#define MBEDTLS_HAVE_TIME_DATE
#define MBEDTLS_HKDF_C
#define MBEDTLS_HMAC_DRBG_C
#define MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#define MBEDTLS_MD5_C
#define MBEDTLS_MD_C
#define MBEDTLS_NET_C
#define MBEDTLS_OID_C
#define MBEDTLS_PADLOCK_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PEM_WRITE_C
#define MBEDTLS_PKCS12_C
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_PKCS1_V21
#define MBEDTLS_PKCS5_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_PARSE_EC_EXTENDED
#define MBEDTLS_PK_RSA_ALT_SUPPORT
#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_POLY1305_C
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_PSA_CRYPTO_STORAGE_C
#define MBEDTLS_PSA_ITS_FILE_C
#define MBEDTLS_REMOVE_3DES_CIPHERSUITES
#define MBEDTLS_REMOVE_ARC4_CIPHERSUITES
#define MBEDTLS_RIPEMD160_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA512_C
#define MBEDTLS_SSL_ALL_ALERT_MESSAGES
#define MBEDTLS_SSL_ALPN
#define MBEDTLS_SSL_CACHE_C
#define MBEDTLS_SSL_CBC_RECORD_SPLITTING
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_CONTEXT_SERIALIZATION
#define MBEDTLS_SSL_COOKIE_C
#define MBEDTLS_SSL_DTLS_ANTI_REPLAY
#define MBEDTLS_SSL_DTLS_BADMAC_LIMIT
#define MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#define MBEDTLS_SSL_DTLS_HELLO_VERIFY
#define MBEDTLS_SSL_ENCRYPT_THEN_MAC
#define MBEDTLS_SSL_EXPORT_KEYS
#define MBEDTLS_SSL_EXTENDED_MASTER_SECRET
#define MBEDTLS_SSL_FALLBACK_SCSV
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define MBEDTLS_SSL_MAX_FRAGMENT_LENGTH
#define MBEDTLS_SSL_PROTO_DTLS
#define MBEDTLS_SSL_PROTO_TLS1
#define MBEDTLS_SSL_PROTO_TLS1_1
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_RECORD_CHECKING
#define MBEDTLS_SSL_RENEGOTIATION
#define MBEDTLS_SSL_SERVER_NAME_INDICATION
#define MBEDTLS_SSL_SESSION_TICKETS
#define MBEDTLS_SSL_SRV_C
#define MBEDTLS_SSL_TICKET_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_TRUNCATED_HMAC
#define MBEDTLS_TIMING_C
#define MBEDTLS_VERSION_C
#define MBEDTLS_VERSION_FEATURES
#define MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE
#define MBEDTLS_X509_CHECK_KEY_USAGE
#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_CRL_PARSE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CSR_PARSE_C
#define MBEDTLS_X509_CSR_WRITE_C
#define MBEDTLS_X509_RSASSA_PSS_SUPPORT
#define MBEDTLS_X509_USE_C
#define MBEDTLS_XTEA_C

#if ME_UNIX_LIKE
    #define MBEDTLS_DEPRECATED_WARNING
#endif
#define MBEDTLS_DEPRECATED_REMOVED

#if ME_COM_MPR || ME_MPR_PRODUCT || ME_MULTITHREAD
    #define MBEDTLS_THREADING_C
    #define MBEDTLS_THREADING_ALT
    typedef struct MprMutex* mbedtls_threading_mutex_t;
#endif

#if ME_DEBUG
    #define MBEDTLS_SSL_DEBUG_ALL
    #define MBEDTLS_DEBUG_C
#endif

#if ME_CPU_ARCH == ME_CPU_X86 || ME_CPU_ARCH == ME_CPU_X64
    #define MBEDTLS_HAVE_SSE2
#endif

/*
    Map MakeMe configuration into MbedTLS defines.
    If mbedtls.NAME is defined, then override the MbedTLS definition from config.h
    mbedtls.compact defines an optimized general compact/embedded configuration.
 */
#ifndef ME_MBEDTLS_COMPACT
    #define ME_MBEDTLS_COMPACT 0
#endif

#if ME_MBEDTLS_COMPACT
    #undef MBEDTLS_AES_ROM_TABLES
    #undef MBEDTLS_BLOWFISH_C
    #undef MBEDTLS_DES_C
    #undef MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
    #undef MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
    #undef MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
    #undef MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
    #undef MBEDTLS_PADLOCK_C
    #undef MBEDTLS_PEM_WRITE_C
    #undef MBEDTLS_RIPEMD160_C
    #undef MBEDTLS_SSL3
    #undef MBEDTLS_SSL_PROTO_DTLS
    #undef MBEDTLS_SSL_DTLS_ANTI_REPLAY
    #undef MBEDTLS_SSL_DTLS_HELLO_VERIFY
    #undef MBEDTLS_SSL_DTLS_BADMAC_LIMIT
    #undef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
    #undef MBEDTLS_TIMING_C
    #undef MBEDTLS_VERSION_C
    #undef MBEDTLS_VERSION_FEATURES
    #undef MBEDTLS_XTEA_C
    #undef MBEDTLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO
    #undef MBEDTLS_REMOVE_ARC4_CIPHERSUITES
#endif

/*
    Feature selection based on main.me settings.mbedtls configuration.
 */
#if ME_MBEDTLS_AES_ROM_TABLES
    #define MBEDTLS_AES_ROM_TABLES
#elif defined(ME_MBEDTLS_AES_ROM_TABLES) && ME_MBEDTLS_AES_ROM_TABLES == 0
    #undef MBEDTLS_AES_ROM_TABLES
#endif

#if ME_MBEDTLS_ARC4
    #define MBEDTLS_ARC4_C
#elif defined(ME_MBEDTLS_ARC4) && ME_MBEDTLS_ARC4 == 0
    #undef MBEDTLS_ARC4_C
    #define MBEDTLS_REMOVE_ARC4_CIPHERSUITES
#endif

#if ME_MBEDTLS_CAMELLIA
    #define MBEDTLS_CAMELLIA_C
#elif defined(ME_MBEDTLS_CAMELLIA) && ME_MBEDTLS_CAMELLIA == 0
    #undef MBEDTLS_CAMELLIA_C
#endif

#if ME_MBEDTLS_CBC
    #define MBEDTLS_CIPHER_MODE_CBC
#elif defined(ME_MBEDTLS_CBC) && ME_MBEDTLS_CBC == 0
    #undef MBEDTLS_CIPHER_MODE_CBC
#endif

#if ME_MBEDTLS_CCM
    #define MBEDTLS_CCM_C
#elif defined(ME_MBEDTLS_CCM) && ME_MBEDTLS_CCM == 0
    #undef MBEDTLS_CCM_C
#endif

#if ME_MBEDTLS_DES
    #define MBEDTLS_DES_C
#elif defined(ME_MBEDTLS_DES) && ME_MBEDTLS_DES == 0
    #undef MBEDTLS_DES_C
#endif

#if ME_MBEDTLS_PADLOCK
    #define MBEDTLS_PADLOCK_C
#elif defined(ME_MBEDTLS_PADLOCK) && ME_MBEDTLS_PADLOCK == 0
    #undef MBEDTLS_PADLOCK_C
#endif

#if ME_MBEDTLS_PSK
    #define MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
    #define MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
    #define MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
    #define MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#elif defined(ME_MBEDTLS_PSK) && ME_MBEDTLS_PSK == 0
    #undef MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
    #undef MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
    #undef MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
    #undef MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#endif

#if ME_MBEDTLS_XTEA
    #define MBEDTLS_XTEA_C
#elif defined(ME_MBEDTLS_XTEA) && ME_MBEDTLS_XTEA == 0
    #undef MBEDTLS_XTEA_C
#endif

#ifndef MBEDTLS_SSL_CIPHERSUITES
    /*
        Modified to push down to remove obsolete SHA-1 ciphers
     */
    #define MBEDTLS_SSL_CIPHERSUITES \
    \
    /* All AES-256 ephemeral suites */ \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, \
    MBEDTLS_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_CCM, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_256_CCM, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, \
    MBEDTLS_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_256_CCM_8, \
    \
    /* All AES-128 ephemeral suites */ \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, \
    MBEDTLS_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_CCM, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_128_CCM, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, \
    MBEDTLS_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_128_CCM_8, \
    \
    /* All AES-256 suites */ \
    MBEDTLS_TLS_RSA_WITH_AES_256_GCM_SHA384, \
    MBEDTLS_TLS_RSA_WITH_AES_256_CCM, \
    MBEDTLS_TLS_RSA_WITH_AES_256_CBC_SHA256, \
    MBEDTLS_TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, \
    MBEDTLS_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, \
    MBEDTLS_TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, \
    MBEDTLS_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, \
    MBEDTLS_TLS_RSA_WITH_AES_256_CCM_8, \
    \
    /* All AES-128 suites */ \
    MBEDTLS_TLS_RSA_WITH_AES_128_GCM_SHA256, \
    MBEDTLS_TLS_RSA_WITH_AES_128_CCM, \
    MBEDTLS_TLS_RSA_WITH_AES_128_CBC_SHA256, \
    MBEDTLS_TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, \
    MBEDTLS_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, \
    MBEDTLS_TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, \
    MBEDTLS_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, \
    MBEDTLS_TLS_RSA_WITH_AES_128_CCM_8, \
    \
    /* Obsolete Compatibility suites  */ \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, \
    MBEDTLS_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_256_CBC_SHA, \
    MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, \
    MBEDTLS_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, \
    MBEDTLS_TLS_DHE_RSA_WITH_AES_128_CBC_SHA, \
    MBEDTLS_TLS_RSA_WITH_AES_256_CBC_SHA, \
    MBEDTLS_TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, \
    MBEDTLS_TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, \
    MBEDTLS_TLS_RSA_WITH_AES_128_CBC_SHA, \
    MBEDTLS_TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, \
    MBEDTLS_TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
#endif

#endif /* MBEDTLS_CONFIG_H */

